version: '2'
services:
  mysql:
    restart: always
    container_name: "mysql"
    build: ./data/mysql/
    volumes:
      - "./data/mysql/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: my_app
      TZ: "Asia/Tokyo"
  nginx:
    restart: always
    container_name: "nginx"
    image: "nginx:mainline-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/nginx/conf:/etc/nginx/"
      - "./work:/var/www/html"
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - phpfpm
    links:
      - phpfpm
  phpfpm:
    restart: always
    build: ./data/phpfpm/
    container_name: "phpfpm"
    volumes:
      - "./work:/var/www/html"
    ports:
      - "9000:9000"
      - "9090:9090"
    depends_on:
      - mysql
      - smtp
    links:
      - mysql
      - smtp
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    links:
      - mysql
    ports:
      - "8000:80"
    volumes:
      - "./data/phpmyadmin/sessions:/sessions"
  smtp:
    image: mailhog/mailhog
    container_name: "smtp"
    ports:
     - "8025:8025"
     - "1025:1025" 
